# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

formats: all

python:
   install:
      - requirements: requirements_dev.txt
      - method: pip
        path: .
